import { MigrationInterface, QueryRunner } from 'typeorm';

export class FixCascadeDeleteRelations1735689000000
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    // CHANGES FOR children.parentId -> SET NULL (do not cascade delete children when parent removed)
    await queryRunner.query(
      `ALTER TABLE "children" DROP CONSTRAINT IF EXISTS "FK_children_parent_id"`,
    );

    // some databases might have auto-generated constraint names; drop any FK on parentId
    await this.dropFkByColumn(queryRunner, 'children', 'parentId');

    await queryRunner.query(
      `ALTER TABLE "children" ALTER COLUMN "parentId" DROP NOT NULL`,
    );

    await queryRunner.query(
      `ALTER TABLE "children" ADD CONSTRAINT "FK_children_parent_id" 
       FOREIGN KEY ("parentId") REFERENCES "users"("id") 
       ON DELETE SET NULL ON UPDATE CASCADE`,
    );

    // groups.caregiverId -> SET NULL
    await queryRunner.query(
      `ALTER TABLE "groups" DROP CONSTRAINT IF EXISTS "FK_groups_caregiver_id"`,
    );
    await this.dropFkByColumn(queryRunner, 'groups', 'caregiverId');

    await queryRunner.query(
      `ALTER TABLE "groups" ADD CONSTRAINT "FK_groups_caregiver_id" 
       FOREIGN KEY ("caregiverId") REFERENCES "users"("id") 
       ON DELETE SET NULL ON UPDATE CASCADE`,
    );

    // parents.userId -> CASCADE (this row is just metadata linked to users)
    await queryRunner.query(
      `ALTER TABLE "parents" DROP CONSTRAINT IF EXISTS "FK_parents_user_id"`,
    );
    await this.dropFkByColumn(queryRunner, 'parents', 'userId');

    await queryRunner.query(
      `ALTER TABLE "parents" ADD CONSTRAINT "FK_parents_user_id" 
       FOREIGN KEY ("userId") REFERENCES "users"("id") 
       ON DELETE CASCADE ON UPDATE CASCADE`,
    );

    // caregivers.userId -> CASCADE
    await queryRunner.query(
      `ALTER TABLE "caregivers" DROP CONSTRAINT IF EXISTS "FK_caregivers_user_id"`,
    );
    await this.dropFkByColumn(queryRunner, 'caregivers', 'userId');

    await queryRunner.query(
      `ALTER TABLE "caregivers" ADD CONSTRAINT "FK_caregivers_user_id" 
       FOREIGN KEY ("userId") REFERENCES "users"("id") 
       ON DELETE CASCADE ON UPDATE CASCADE`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Revert children.parentId to NOT NULL + CASCADE
    await queryRunner.query(
      `ALTER TABLE "children" DROP CONSTRAINT IF EXISTS "FK_children_parent_id"`,
    );
    await this.dropFkByColumn(queryRunner, 'children', 'parentId');

    await queryRunner.query(
      `ALTER TABLE "children" ALTER COLUMN "parentId" SET NOT NULL`,
    );

    await queryRunner.query(
      `ALTER TABLE "children" ADD CONSTRAINT "FK_children_parent_id" 
       FOREIGN KEY ("parentId") REFERENCES "users"("id") 
       ON DELETE CASCADE ON UPDATE CASCADE`,
    );

    // Revert groups.caregiverId to default (no onDelete) -> equivalent to RESTRICT
    await queryRunner.query(
      `ALTER TABLE "groups" DROP CONSTRAINT IF EXISTS "FK_groups_caregiver_id"`,
    );
    await this.dropFkByColumn(queryRunner, 'groups', 'caregiverId');

    await queryRunner.query(
      `ALTER TABLE "groups" ADD CONSTRAINT "FK_groups_caregiver_id" 
       FOREIGN KEY ("caregiverId") REFERENCES "users"("id") 
       ON UPDATE CASCADE`,
    );

    // Revert parents.userId (no CASCADE)
    await queryRunner.query(
      `ALTER TABLE "parents" DROP CONSTRAINT IF EXISTS "FK_parents_user_id"`,
    );
    await this.dropFkByColumn(queryRunner, 'parents', 'userId');

    await queryRunner.query(
      `ALTER TABLE "parents" ADD CONSTRAINT "FK_parents_user_id" 
       FOREIGN KEY ("userId") REFERENCES "users"("id")`,
    );

    // Revert caregivers.userId (no CASCADE)
    await queryRunner.query(
      `ALTER TABLE "caregivers" DROP CONSTRAINT IF EXISTS "FK_caregivers_user_id"`,
    );
    await this.dropFkByColumn(queryRunner, 'caregivers', 'userId');

    await queryRunner.query(
      `ALTER TABLE "caregivers" ADD CONSTRAINT "FK_caregivers_user_id" 
       FOREIGN KEY ("userId") REFERENCES "users"("id")`,
    );
  }

  private async doesForeignKeyExist(
    queryRunner: QueryRunner,
    tableName: string,
    constraintName: string,
  ): Promise<boolean> {
    const result = await queryRunner.query(
      `SELECT constraint_name FROM information_schema.table_constraints 
       WHERE table_name = $1 AND constraint_name = $2`,
      [tableName, constraintName],
    );
    return result.length > 0;
  }

  // Drop any FK constraint by column name (useful when names are autogenerated)
  private async dropFkByColumn(
    queryRunner: QueryRunner,
    tableName: string,
    columnName: string,
  ): Promise<void> {
    const constraints: Array<{ constraint_name: string }> =
      await queryRunner.query(
        `SELECT tc.constraint_name
       FROM information_schema.table_constraints tc
       JOIN information_schema.key_column_usage kcu
         ON tc.constraint_name = kcu.constraint_name
       WHERE tc.constraint_type = 'FOREIGN KEY'
         AND tc.table_name = $1
         AND kcu.column_name = $2`,
        [tableName, columnName],
      );

    for (const row of constraints) {
      await queryRunner.query(
        `ALTER TABLE "${tableName}" DROP CONSTRAINT IF EXISTS "${row.constraint_name}"`,
      );
    }
  }
}
